### ISSUE TITLE
Request Costum Delay

### ISSUE THREAD

**Issue by aagilang** [JoaoCampelo/Presearch_Bot#1]
can i request costum delay time on search..

**Comment by JoaoCampelo** [comment]
yes, you can change the delay time between searches, in the configuration.py file there is a delay field where you can put the delay time in seconds.
Right now it's set to 4 seconds but I think if you put less time between searches it will make you have to run the bot more than once so that the preserarch counts all 25 daily searches, it's not a bot problem, but the way to count the search engine itself.
