### ISSUE TITLE
Cant login

### ISSUE THREAD

**Issue by ecomcodeLab** [JoaoCampelo/Presearch_Bot#2]
Hi
i noticed that it opens a strange profil 1 but its not my profil1 i set up a new one thats open via ink to profile 1 (made from chrome itself on desktop)
the normal first profil of chrome is i think default

alsow after its open that strange profil  i log in make all things and then i am logged in i hit enter on cmd but i get code error

DevTools listening on ws://127.0.0.1:7101/devtools/browser/a6503100-8211-4e9a-83e9-ca55bd7bee73
[2296:1624:1125/184726.298:ERROR:device_event_log_impl.cc(215)] [18:47:26.297] Bluetooth: bluetooth_adapter_winrt.cc:1164 RequestRadioAccessAsync failed: RadioAccessStatus::DeniedByUserWill not be able to change radio power.
Press Enter after proving you´re not a robot:

Something went wrong!
Please re-run the bot to try again

Unable to login to your Presearch account, please re-run the bot to try to login.

**Comment by JoaoCampelo** [comment]
Hi,
Thanks for using my bot.
As for the issue of a profile with the name "Profile 1" being used, it is a different profile from your default profile, created in the bot, so that the bot does not access your profile information, such as passwords, extensions ...
As for the question you indicate about the login, I think that you may be doing things incorrectly, you have to press Enter in the command line right after completing the challenge to prove that you are not a robot, and from what I understood in the your comment you completed this challenge, logged in and only then did you enter the cmd.
Finally, the question of the error "Bluetooth: bluetooth_adapter_winrt.cc:1164" which indicates, this is not a problem, just log messages made by the WebDriver itself, I already wanted to have hidden these messages but it still hadn't been possible, but if I do again get from the repository already has this issue resolved, the log messages no longer appear.

Then try to follow the indication I gave you to Login to your Presearch account, and please let me know if you succeeded.

**Comment by ecomcodeLab** [comment]
its working new version changes works and yes i clicked on login after challange captcha but we have to click when we have done challange so the bot does the rest with login

is there a way to write this inside the bot.

alsow do you know if it is a way to tell the headless mode or to tell a size of the window??? i mean full window is not working at my pc.
i test it and bot works alsow in half of the window so maybe we can get a option to change xy size :)

and second the chromedriver make a dos windows thats stays open i use some other bots and noticed there is no dos window of chromedriver. so maybe there is a trick do make it hidden

and to the chrome profil i have default release / profile 1 / profile 2. But the bot use a Profile 1 thats not existing. How is this working

**Comment by ecomcodeLab** [comment]
maybe you can implement the addon nopecha. its a captcha breaker and works great with recaptcha and hcaptcha. free user have 200 captchas free every 24h then they refill. thats so nice 

like i see you spoof the cookies right? can you show me how you do this. i need this for other projects

After all Searches were done the chromedriver cmd window stay open can we close this with python

RANDOM DELAY:
Maybe a Random Delay will be good for import Random we can use this
randomsec = (random.randint(1,15))

**Comment by JoaoCampelo** [comment]
Thanks for the suggestions, as soon as I have a bit of time I'll research your suggestions and I'll be able to implement them.
As for the delay time, you can change it in the configurations.py file, changing the delay field, I keep it at 4 seconds to make sure that it does all the searches with just one pass from the bot, because I already tested it with a delay smaller and the Presearch algorithm did not account for all searches.

To use the browser in full screen, I use the driver.maximize_window, I know you can indicate the size we want but I would have to do an internet search to tell you how, I normally don't use it so I don't know how to do it off the top of my head.
Yes, I keep the cookies and use them to login later, you can see this in the Login function, where it tests whether there are cookies, and if they exist, enter the login_with_cookies function to login. If there are no cookies, let the login normally and then use the line "pickle.dump(driver.get_cookies() , open("ExtraFiles//cookies.pkl","wb"))" to create a file with the cookies . For this we have to import the Pickle module.
