### ISSUE TITLE
I Try to open it with a bat file

### ISSUE THREAD

**Issue by ecomcodeLab** [JoaoCampelo/Presearch_Bot#4]
i try to open it with bash bat. then i got this error
this is code of bat

`cd C:\Users\orbsmart2\Downloads\Python Billy\Presearch & REM First change to the batch file folder

"C:\Users\2\AppData\Local\Programs\Python\Python37\python.exe" folder1\Presearch_Bot\Presearch_Bot.py

"C:\Users\2\AppData\Local\Programs\Python\Python37\python.exe" folder2\Presearch_Bot\Presearch_Bot.py

"C:\Users\2\AppData\Local\Programs\Python\Python37\python.exe" folder3\Presearch_Bot\Presearch_Bot.py
`

resault:
C:\Users\2\Downloads\Python b\Presearch>"C:\Users\2\AppData\Local\Programs\Python\Python37\python.exe" folder1\Presearch_Bot\Presearch_Bot.py
Traceback (most recent call last):
  File "folder1\Presearch_Bot\Presearch_Bot.py", line 15, in <module>
    words = open("ExtraFiles//words.txt", "r").readlines()
FileNotFoundError: [Errno 2] No such file or directory: 'ExtraFiles//words.txt'

normaly this works i tryed this with other python scripts

**Comment by JoaoCampelo** [comment]
From the error you report, I'm only understanding two hypotheses, either you don't have that words.txt file, or you don't have the folders as they should be, the ExtraFiles folder has to be at the level of the Presearch_Bot.py file.

You have to try to debug to understand what is happening there on your machine.

**Comment by ecomcodeLab** [comment]
i have the folder were  Presearch_Bot.py when i directly use the py it works alsow if i make a bat with 
`python  Presearch_Bot.py`

works alsow but not when i try to open this bat via task scheduler it instantly close
alsow when i try the above post code

i get that error i think python looks in wrong folder or something or the words = open("ExtraFiles//words.txt", "r").readlines()
should be something else maybe %USERPROFILE%


at a similar bot project i found this:
```

def getWords():
    with open('./files/words.txt') as f:
        return f.readlines()
```

**Comment by JoaoCampelo** [comment]
I don't know how the task scheduler works, but it looks like it's trying to run the Presearch_Bot.py file in another folder, as its line indicates:

C:\Users\2\Downloads\Python b\Presearch>"C:\Users\2\AppData\Local\Programs\Python\Python37\python.exe" folder1\Presearch_Bot\Presearch_Bot.py

And if so, it can't get to the other files in the project.
As for this error, I can't help you, but in a future version, an alteration will be made so that it is only necessary to run the Presearch_Bot.py file once and then every day at a certain time it goes back to doing the searches.
But this functionality will only be done when I have a little time available.
