### ISSUE TITLE
can you add a close

### ISSUE THREAD

**Issue by ecomcodeLab** [JoaoCampelo/Presearch_Bot#6]
hi after all finish and worked or not the python file will stay open can you please set a exit inside  so it  writes  how much coins we get and then exit the script 

thank you

**Comment by JoaoCampelo** [comment]
Hi, as I think I told you on another occasion, I'm not going to change this behavior, I want that when the bot finishes doing the daily searches it remains open so that I can see what happened during its execution.
If you want, you are free to fork my project and make any changes you want to make the bot work the way you want.
